 # PteroStats config
# If you need help, join our discord server here: https://discord.gg/zv6maQRah3

# Bot Configuration
token: "MTIxMjcxMjEyODUwMzQ4MDM0MQ.GVLsnh.zrhwtQMbjtTPeaMThl_64MiEe6WDnUndjU_RpU"
presence:
  text: "NixonNodes.com"
  type: "watching" # can be 'watching', 'playing', 'listening', or 'competing'. 'streaming' is not working for now
  status: "online" # can be 'online', 'idle', 'dnd', or 'invisible'

# Discord Channel and Refresh Time Configuration
channel: "1240289713395470346"
refresh: 60 # How much time the bot will refresh the stats
timeout: 1 # How much time to wait for a node to respond to the bot (if you change this, it will add more time to refresh the stats)

# Panel Configuration
panel:
  url: "ptlc_kZty4ARoztedVgIu7F5cFJE1uymJ3POByrUwrlhx9To"
  key: "https://panel.nixonnodes.com/"

# Message and Embed Configuration
# set the option as '' if you want to disable it
message:
  content: ""
  attachment: "" # If you enable attachment on message it will upload the attachment first before sending or editing message and will result in delayed stats

embed:
  title: "NixonNodes"
  color: "32CD32"
  description: "Next update {{time}}" # You can use {{time}} to make "in X seconds" time format
  footer: "Nixon"
  timestamp: true
  thumbnail: "https://cdn.discordapp.com/icons/1178200262947647528/1f28bcba182ebc928a525fc89530bf39.png"
  image: ""
  field:
    title: ""
    description: "" # You can use {{time}} to make "in X seconds" time format

# Message Button Configuration
button:
  enable: false
  btn1:
    label: "PteroStats"
    url: "https://github.com/HirziDevs/PteroStats"
  btn2:
    label: ""
    url: ""
  btn3:
    label: ""
    url: ""
  btn4:
    label: ""
    url: ""
  btn5:
    label: ""
    url: ""

# Status Message Configuration
# How to use custom emoji: https://github.com/HirziDevs/PteroStats#using-custom-emoji
status:
  online: ":green_circle: Online"
  offline: ":red_circle: Offline"

# Nodes Settings
# How to get nodes id: https://github.com/HirziDevs/PteroStats#blacklist-nodes
nodes_settings:
  blacklist: [] # You can add node id to remove the node from status embed (Example: "blacklist: [1]")
  details: false # enable nodes details i.e memory and disk usage
  servers: true
  location: true
  allocations: true
  unit: "gb" # Allowed values- "gb", "mb", "tb", or "percent"

# Panel Users and Servers Settings
panel_settings:
  status: true # enable panel stats under nodes stats
  servers: true
  users: true

# Mentions a User or Role if any node is offline (this feature is still in testing, please report if you have a problem)
mentions: # to enable atleast put 1 ID on user or role bellow
  user: ['548867757517570058'] # Put User ID here (Example: "user: ['548867757517570058', '816219634390663230']")
  role: ['796083838236622858'] # Put Role ID here (Example: "role: ['796083838236622858', '858198863973187585']")
  channel: "796083838236622858 " # Put Channel ID here for the logging

# Log error to console if a server offline (enable this when you have a problem that you want to report)
log_error: false # set to "true" to enable
